name: Baseline check

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  baseline:
    name: Baseline
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/baseline-check.yml@d2a2353830cf211a9f18f3585085016766294dff  # main
    with:
      has-board: true
      python-version: "3.14"
