name: Baseline check

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  baseline:
    name: Baseline
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/baseline-check.yml@fb907a46b00693a117ca6b975da6e7b0f8238491  # main
    with:
      has-board: true
      python-version: "3.14"
