name: Lint workflows

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint-workflows:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@fb907a46b00693a117ca6b975da6e7b0f8238491
    with:
      run-actionlint: true
      run-zizmor: true
