---
name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    if: contains(join(github.event.head_commit.modified, ' '), 'changelog.d/') || contains(join(github.event.head_commit.added, ' '), 'changelog.d/')
    permissions:
      contents: write
      id-token: write   # OIDC trusted publishing to PyPI
      pull-requests: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/auto-release.yml@5cd8c1facb02299da618979e7a55f1953f9c075a
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
